#!/usr/bin/env python
from __future__ import print_function
from setuptools import setup


# Version
# N.B., this is versioned separately from rcomp clients
MAJOR = 0
MINOR = 1
MICRO = 0

rcomp_version = '{major}.{minor}.{micro}'.format(major=MAJOR, minor=MINOR, micro=MICRO)

with open('rcompserv/_version.py', 'w') as f:
    f.write("""# Automatically generated by setup.py of rcompserv. Do not edit.
version = '{version}'""".format(version=rcomp_version))


setup(name='rcompserv',
      version=rcomp_version,
      author='Scott C. Livingston',
      author_email='slivingston@cds.caltech.edu',
      url='https://github.com/slivingston/rcomp',
      license='BSD',
      description='',
      packages=['rcompserv'],
      install_requires=['aiohttp', 'redis'],
      entry_points={'console_scripts': ['rcompserv = rcompserv.cli:main']},
      classifiers=['Programming Language :: Python :: 3',
                   'Programming Language :: Python :: 3.5']
      )
